// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Services;

namespace Movies.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20190324183824_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Movies.Model.BookingTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MovieDetailsId");

                    b.Property<int>("MovieId");

                    b.Property<int>("SeatNo");

                    b.Property<int>("UserId");

                    b.Property<int>("price");

                    b.Property<DateTime>("time");

                    b.HasKey("Id");

                    b.HasIndex("MovieDetailsId");

                    b.ToTable("BookingTables");
                });

            modelBuilder.Entity("Movies.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<int>("MovieId");

                    b.Property<string>("SeatNo");

                    b.Property<DateTime>("date");

                    b.Property<int>("price");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Movies.Model.MovieDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAndTime");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Pictures");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("MovieDetails");
                });

            modelBuilder.Entity("Movies.Model.BookingTable", b =>
                {
                    b.HasOne("Movies.Model.MovieDetails", "moviedetails")
                        .WithMany("bookings")
                        .HasForeignKey("MovieDetailsId");
                });
#pragma warning restore 612, 618
        }
    }
}
